### PR TITLE
HBASE-27978 Add spotless in hbase-operator-tools pre-commit check

### PR DESCRIPTION
**Pull request by NihalJain**
- Added a new file for custom hbase-personality.sh having spotless plugin
- Updated Jenkinsfile to point to the above file

### CODE REVIEW

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/1/console in case of problems.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 48s |  master passed  |
| +1 :green_heart: |  compile  |   0m 10s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  7s |  master passed  |
| -1 :x: |  spotless  |   0m  7s |  branch has 63 errors when running spotless:check, run spotless:apply to fix.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m  5s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  6s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   4m 55s |  hbase-hbck2 in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   8m 47s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/136 |
| Optional Tests | dupname asflicense spotless shellcheck shelldocs javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux a7081fa87b6c 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / 0bf6ee1 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| spotless | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/1/artifact/yetus-precommit-check/output/branch-spotless.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/1/testReport/ |
| Max. process+thread count | 1241 (vs. ulimit of 5000) |
| modules | C: hbase-hbck2 U: hbase-hbck2 |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/1/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
- As seen in the above build spotless is added to pre-commit. 
- Also, spotless fails for master as we have existing spotless issues in current master code. 
- With this patch and spotless fix in `hbase-hbck2/src/main/java/org/apache/hbase/HBCK2.java`, spotless for patch is success. 

Please let me know if need to raise another PR to fix spotless 1st, and then re-base and re-trigger this PR. 

CC: @Apache9 , @petersomogyi , @wchevreuil

**Comment by NihalJain** [comment]
> Better to fix the spotless issue with a separated issue, so we can make the PR cleaner.
> 
> Thanks.

Sure @Apache9 let me do that right away. Thanks for quick review.

**Comment by NihalJain** [comment]
Raised https://github.com/apache/hbase-operator-tools/pull/137 to fix existing spotless issues.
CC: @Apache9

**Comment by NihalJain** [comment]
Rebased the code!

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/2/console in case of problems.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 31s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  spotless  |   0m  7s |  branch has no errors when running spotless:check.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  2s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m  5s |  patch has no errors when running spotless:check.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   1m 13s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/136 |
| Optional Tests | dupname asflicense spotless shellcheck shelldocs |
| uname | Linux 2ee8f7a3f95d 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / ffef531 |
| Max. process+thread count | 34 (vs. ulimit of 5000) |
| modules | C:  U:  |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-136/2/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
Gentle ping @Apache9 @petersomogyi @wchevreuil Please let me know, if this is good to go.

**Review by petersomogyi — APPROVED** [review]
lgtm

**Pull request merged**
