### PR TITLE
HBASE-28935 [HBCK2] filesystem command always report region hole

### PR DESCRIPTION
**Pull request by haosenchen**
[HBCK2] filesystem command always report region hole and doesn't exit automatically

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m  2s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  master passed  |
| +1 :green_heart: |  spotless  |   0m 10s |  branch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  spotless  |   0m  8s |  patch has 36 errors when running spotless:check, run spotless:apply to fix.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   6m 20s |  hbase-hbck2 in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  7s |  The patch does not generate ASF License warnings.  |
|  |   |  11m 29s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestHBCKCommandLineParsing |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/147 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs spotless checkstyle compile |
| uname | Linux 2d951784824a 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / f69bcbb |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| spotless | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/1/artifact/yetus-precommit-check/output/patch-spotless.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/1/artifact/yetus-precommit-check/output/patch-unit-hbase-hbck2.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/1/testReport/ |
| Max. process+thread count | 1191 (vs. ulimit of 5000) |
| modules | C: hbase-hbck2 U: hbase-hbck2 |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/1/console |
| versions | git=2.30.2 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m  5s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 55s |  master passed  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  master passed  |
| +1 :green_heart: |  spotless  |   0m 11s |  branch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m  7s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   5m 47s |  hbase-hbck2 in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  8s |  The patch does not generate ASF License warnings.  |
|  |   |  10m 48s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestHBCKCommandLineParsing |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/147 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs spotless checkstyle compile |
| uname | Linux d6d4bd11f765 5.4.0-195-generic #215-Ubuntu SMP Fri Aug 2 18:28:05 UTC 2024 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / f69bcbb |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/2/artifact/yetus-precommit-check/output/patch-unit-hbase-hbck2.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/2/testReport/ |
| Max. process+thread count | 1242 (vs. ulimit of 5000) |
| modules | C: hbase-hbck2 U: hbase-hbck2 |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/2/console |
| versions | git=2.30.2 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 46s |  master passed  |
| +1 :green_heart: |  compile  |   0m 10s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  7s |  master passed  |
| +1 :green_heart: |  spotless  |   0m  6s |  branch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m  5s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  6s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   5m  0s |  hbase-hbck2 in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   7m 52s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/147 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs spotless checkstyle compile |
| uname | Linux 4f0b53c2bb5b 5.4.0-195-generic #215-Ubuntu SMP Fri Aug 2 18:28:05 UTC 2024 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / f69bcbb |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/3/testReport/ |
| Max. process+thread count | 1263 (vs. ulimit of 5000) |
| modules | C: hbase-hbck2 U: hbase-hbck2 |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-147/3/console |
| versions | git=2.30.2 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by bsglz — APPROVED** [review]
+1

**Pull request merged**
