### PR TITLE
HBASE-28768 hbase-table-reporter shoud use the hbase.version declared in the parent pom.xml and use junit for UT

### PR DESCRIPTION
**Pull request by guluo2016**
Details see : [HBASE-28768](https://issues.apache.org/jira/browse/HBASE-28768)

Related discussions： #142

**Self testing：**
```shell
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hbase.reporter.TestTableReporter
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.06 s - in org.apache.hbase.reporter.TestTableReporter
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache HBase Operator Tools 1.3.0-SNAPSHOT:
[INFO] 
[INFO] Apache HBase Operator Tools ........................ SUCCESS [  1.103 s]
[INFO] Apache HBase - Table Reporter ...................... SUCCESS [  2.663 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.948 s
```

**Building:**  
```shell
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache HBase Operator Tools 1.3.0-SNAPSHOT:
[INFO] 
[INFO] Apache HBase Operator Tools ........................ SUCCESS [  1.602 s]
[INFO] Apache HBase - Table Reporter ...................... SUCCESS [  8.034 s]
[INFO] Apache HBase - HBCK2 ............................... SUCCESS [  6.227 s]
[INFO] Apache HBase - HBase Tools ......................... SUCCESS [  1.398 s]
[INFO] Apache HBase Operator Tools - Assembly ............. SUCCESS [  0.047 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.472 s
```

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 49s |  master passed  |
| +1 :green_heart: |  compile  |   0m  6s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  master passed  |
| +1 :green_heart: |  spotless  |   0m  6s |  branch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  2s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  spotless  |   0m  5s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  4s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  7s |  hbase-table-reporter in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  5s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 27s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-144/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/144 |
| Optional Tests | dupname asflicense javac javadoc unit spotless xml compile spotbugs findbugs checkstyle |
| uname | Linux b7d7ce32b5d4 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / 7c738fc |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-144/1/testReport/ |
| Max. process+thread count | 38 (vs. ulimit of 5000) |
| modules | C: hbase-table-reporter U: hbase-table-reporter |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-144/1/console |
| versions | git=2.30.2 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 28s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 46s |  master passed  |
| +1 :green_heart: |  compile  |   0m  5s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  master passed  |
| +1 :green_heart: |  spotless  |   0m  7s |  branch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  2s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  spotless  |   0m  4s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  javadoc  |   0m  4s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-table-reporter in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 29s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-144/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/144 |
| Optional Tests | dupname asflicense javac javadoc unit spotless xml compile spotbugs findbugs checkstyle |
| uname | Linux 3d9acd7de0b0 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/jenkins/hbase-personality.sh |
| git revision | master / 7c738fc |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-144/2/testReport/ |
| Max. process+thread count | 64 (vs. ulimit of 5000) |
| modules | C: hbase-table-reporter U: hbase-table-reporter |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-144/2/console |
| versions | git=2.30.2 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by pankaj72981 — APPROVED** [review]

**Review by NihalJain — APPROVED** [review]

**Comment by NihalJain** [comment]
Hi @guluo2016 changes lgtm but it would be great it we could we make jira title more descriptive/specific before we commit this.

**Review by NihalJain — APPROVED** [review]

**Comment by NihalJain** [comment]
Hi @guluo2016 please let me know if I am good to merge this?

**Comment by guluo2016** [comment]
> Hi @guluo2016 please let me know if I am good to merge this?

@NihalJain  I think we should merge PR #142 firstly, and then merge the current PR.   

Maybe we need update this PR after merging PR #142  .

**Comment by NihalJain** [comment]
> > Hi @guluo2016 please let me know if I am good to merge this?
> 
> @NihalJain I think we should merge PR #142 firstly, and then merge the current PR.
> 
> Maybe we need update this PR after merging PR #142 .

Ah I thought so, there's some dependency. But is it not other way around?

**Comment by guluo2016** [comment]
> > > Hi @guluo2016 please let me know if I am good to merge this?
> > 
> > 
> > @NihalJain I think we should merge PR #142 firstly, and then merge the current PR.
> > Maybe we need update this PR after merging PR #142 .
> 
> Ah I thought so, there's some dependency. But is it not other way around?


https://github.com/apache/hbase-operator-tools/pull/142#discussion_r1709302683

well,  I think you are right,  you can merge the current PR firstly.

**Comment by NihalJain** [comment]
> well, I think you are right, you can merge the current PR firstly.

Thanks for confirming. I am merging this now.

**Comment by NihalJain** [comment]
Merged to code base. Thank you @guluo2016 for your contribution.

**Pull request merged**
