### PR TITLE
HBASE-27830 Introduce hdfs overlay

### PR DESCRIPTION
**Pull request by ndimiduk**
Depends on #117, #118, #119

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  yamllint  |   0m  0s |  yamllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  hadolint  |   0m  0s |  hadolint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ HBASE-27827-kubernetes-deployment Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 46s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  compile  |   0m 13s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  javadoc  |   0m  8s |  HBASE-27827-kubernetes-deployment passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  8s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 24s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 17s |  the patch passed  |
| -1 :x: |  shellcheck  |   0m  0s |  The patch generated 52 new + 0 unchanged - 0 fixed = 52 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 11s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-kubernetes-deployment in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 13s |  root in the patch passed.  |
| -1 :x: |  asflicense  |   0m 10s |  The patch generated 2 ASF License warnings.  |
|  |   |   9m 58s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/120 |
| Optional Tests | dupname asflicense markdownlint yamllint shellcheck shelldocs xml hadolint javac javadoc unit compile |
| uname | Linux 44c08fbc78fe 5.4.0-1099-aws #107~18.04.1-Ubuntu SMP Fri Mar 17 16:49:05 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | HBASE-27827-kubernetes-deployment / 6455991 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| shellcheck | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/1/artifact/yetus-precommit-check/output/diff-patch-shellcheck.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/1/testReport/ |
| asflicense | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/1/artifact/yetus-precommit-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1263 (vs. ulimit of 5000) |
| modules | C: hbase-kubernetes-deployment . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/1/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  yamllint  |   0m  0s |  yamllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  hadolint  |   0m  0s |  hadolint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ HBASE-27827-kubernetes-deployment Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 57s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  compile  |   0m 13s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  javadoc  |   0m  8s |  HBASE-27827-kubernetes-deployment passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  9s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 24s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 18s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 18s |  the patch passed  |
| -1 :x: |  shellcheck  |   0m  1s |  The patch generated 7 new + 0 unchanged - 0 fixed = 7 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 11s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-kubernetes-deployment in the patch passed.  |
| +1 :green_heart: |  unit  |   6m  7s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 11s |  The patch does not generate ASF License warnings.  |
|  |   |   9m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/120 |
| Optional Tests | dupname asflicense markdownlint yamllint shellcheck shelldocs xml hadolint javac javadoc unit compile |
| uname | Linux f3a444b1cf94 5.4.0-1099-aws #107~18.04.1-Ubuntu SMP Fri Mar 17 16:49:05 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | HBASE-27827-kubernetes-deployment / 6455991 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| shellcheck | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/2/artifact/yetus-precommit-check/output/diff-patch-shellcheck.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/2/testReport/ |
| Max. process+thread count | 1261 (vs. ulimit of 5000) |
| modules | C: hbase-kubernetes-deployment . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/2/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Hmm we should upgrade `shellcheck`. my local 0.9.0 version has no complaints.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  5s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  yamllint  |   0m  0s |  yamllint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  hadolint  |   0m  0s |  hadolint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ HBASE-27827-kubernetes-deployment Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 50s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  compile  |   0m 11s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  javadoc  |   0m  8s |  HBASE-27827-kubernetes-deployment passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  8s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-kubernetes-deployment in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 44s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 10s |  The patch does not generate ASF License warnings.  |
|  |   |   9m 27s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/120 |
| Optional Tests | dupname asflicense markdownlint yamllint shellcheck shelldocs xml hadolint javac javadoc unit compile |
| uname | Linux 691a0827bc3b 5.4.0-1101-aws #109~18.04.1-Ubuntu SMP Mon Apr 24 20:40:49 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | HBASE-27827-kubernetes-deployment / 6455991 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/3/testReport/ |
| Max. process+thread count | 1275 (vs. ulimit of 5000) |
| modules | C: hbase-kubernetes-deployment . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/3/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/console in case of problems.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  yamllint  |   0m  0s |  yamllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 17 new or modified test files.  |
||| _ HBASE-27827-kubernetes-deployment Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 29s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  compile  |   0m 15s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  HBASE-27827-kubernetes-deployment passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  6s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  0s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 23s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 11s |  hbase-kubernetes-deployment in the patch passed.  |
| -1 :x: |  unit  |   5m 50s |  root in the patch failed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-kubernetes-hadoop-image in the patch passed.  |
| -1 :x: |  unit  |   0m  4s |  hbase-kubernetes-kustomize in the patch failed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-kubernetes-testing-image in the patch passed.  |
| -1 :x: |  asflicense  |   0m 23s |  The patch generated 1 ASF License warnings.  |
|  |   |  18m  2s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/120 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs markdownlint javac javadoc unit xml compile yamllint |
| uname | Linux f9d807e19715 5.4.0-1099-aws #107~18.04.1-Ubuntu SMP Fri Mar 17 16:49:05 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | HBASE-27827-kubernetes-deployment / f521479 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/artifact/yetus-precommit-check/output/patch-unit-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/artifact/yetus-precommit-check/output/patch-unit-hbase-kubernetes-deployment_hbase-kubernetes-kustomize.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/testReport/ |
| asflicense | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/artifact/yetus-precommit-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1264 (vs. ulimit of 5000) |
| modules | C: hbase-kubernetes-deployment . hbase-kubernetes-deployment/hbase-kubernetes-hadoop-image hbase-kubernetes-deployment/hbase-kubernetes-kustomize hbase-kubernetes-deployment/hbase-kubernetes-testing-image U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/4/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 hadolint=Haskell Dockerfile Linter 2.12.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/console in case of problems.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  yamllint  |   0m  0s |  yamllint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 17 new or modified test files.  |
||| _ HBASE-27827-kubernetes-deployment Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 36s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 33s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  compile  |   0m 17s |  HBASE-27827-kubernetes-deployment passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  HBASE-27827-kubernetes-deployment passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  6s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m  4s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  1s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 22s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m  9s |  hbase-kubernetes-deployment in the patch failed.  |
| -1 :x: |  unit  |   6m  4s |  root in the patch failed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-kubernetes-hadoop-image in the patch passed.  |
| -1 :x: |  unit  |   0m  9s |  hbase-kubernetes-kustomize in the patch failed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-kubernetes-testing-image in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   |  18m 28s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/120 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs markdownlint javac javadoc unit xml compile yamllint |
| uname | Linux aefd178ef538 5.4.0-1099-aws #107~18.04.1-Ubuntu SMP Fri Mar 17 16:49:05 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | HBASE-27827-kubernetes-deployment / f521479 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/artifact/yetus-precommit-check/output/patch-unit-hbase-kubernetes-deployment.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/artifact/yetus-precommit-check/output/patch-unit-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/artifact/yetus-precommit-check/output/patch-unit-hbase-kubernetes-deployment_hbase-kubernetes-kustomize.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/testReport/ |
| Max. process+thread count | 1259 (vs. ulimit of 5000) |
| modules | C: hbase-kubernetes-deployment . hbase-kubernetes-deployment/hbase-kubernetes-hadoop-image hbase-kubernetes-deployment/hbase-kubernetes-kustomize hbase-kubernetes-deployment/hbase-kubernetes-testing-image U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-120/7/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 hadolint=Haskell Dockerfile Linter 2.12.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Closed in favor of https://github.com/apache/hbase-kustomize/pull/9

**Pull request closed without merging**
