### PR TITLE
HBASE-27977 Add spotless plugin to hbase-operator-tools

### PR DESCRIPTION
**Pull request by NihalJain**
- Added the plugin to pom.xml
- Added the files required by the plugin ( copying them from hbase repo)

### CODE REVIEW

**Comment by NihalJain** [comment]
Commit 1: Added plug-in along with required files
Commit 2:
Ran `mcn spotless:apply` and staged all file changes. We can decide if we want to do this as a separate change to keep things clean.

Let me know what do you all think of this change.

CC: @duo @ndimiduk @wchevreuil

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 16 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 29s |  master passed  |
| +1 :green_heart: |  compile  |   0m 38s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 18s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 25s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 38s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 38s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 24s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-table-reporter in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 31s |  hbase-hbck2 in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 26s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-operator-tools-assembly in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 55s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   |  19m 26s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-132/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/132 |
| Optional Tests | dupname asflicense markdownlint xml shellcheck shelldocs javac javadoc unit compile spotbugs findbugs checkstyle |
| uname | Linux ed2e324f02de 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / efa1916 |
| Default Java | Oracle Corporation-1.8.0_342-b07 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-132/1/testReport/ |
| Max. process+thread count | 1273 (vs. ulimit of 5000) |
| modules | C: hbase-table-reporter hbase-hbck2 hbase-tools hbase-operator-tools-assembly . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Operator-Tools-PreCommit/job/PR-132/1/console |
| versions | git=2.30.2 maven=3.8.6 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by petersomogyi — APPROVED** [review]
I'm fine with the squash of these 2 commits.

**Comment by NihalJain** [comment]
Thank you @petersomogyi for reviewing. Will wait and merge this tomorrow, in case no objections.

**Comment by NihalJain** [comment]
Thanks @petersomogyi, merged to code base!

**Pull request merged**
